import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GptEncoding } from 'gpt-tokenizer/GptEncoding';
import { logger } from '../../shared/logger.js';

// Supported token encoding types (OpenAI encoding names)
export const TOKEN_ENCODINGS = ['o200k_base', 'cl100k_base', 'p50k_base', 'p50k_edit', 'r50k_base'] as const;
export type TokenEncoding = (typeof TOKEN_ENCODINGS)[number];

interface CountTokensOptions {
  disallowedSpecial?: Set<string>;
}

type CountTokensFn = (text: string, options?: CountTokensOptions) => number;

// Treat all text as regular content by disallowing nothing,
// so special tokens like <|endoftext|> are tokenized as ordinary text.
const PLAIN_TEXT_OPTIONS: CountTokensOptions = { disallowedSpecial: new Set() };

// Lazy-loaded countTokens functions keyed by encoding
const encodingModules = new Map<string, CountTokensFn>();

// Some encodings share the same BPE rank data file.
// Mirror the mapping in gpt-tokenizer's resolveEncodingAsync.
const resolveDataName = (encodingName: string): string => {
  if (encodingName === 'p50k_edit') return 'p50k_base';
  if (encodingName === 'o200k_harmony') return 'o200k_base';
  return encodingName;
};

/**
 * Load BPE rank data for a given encoding.
 *
 * Tries a pre-built JSON cache first (generated by scripts/generateBpeCache.mjs
 * during `npm run build`). JSON.parse on a 1.7 MB string runs in ~23ms vs ~200ms
 * for V8 to evaluate the equivalent 2.2 MB JS module with 200K string literals —
 * an 8-9x speedup per worker thread. Falls back to the original JS module import
 * when the JSON cache is not available (e.g., during development before build).
 */
const loadBpeRanks = async (encodingName: TokenEncoding): Promise<readonly (string | readonly number[])[]> => {
  const dataName = resolveDataName(encodingName);

  // Fast path: load from pre-built JSON cache
  try {
    const jsonPath = path.join(path.dirname(fileURLToPath(import.meta.url)), 'data', `${dataName}.json`);
    return JSON.parse(fs.readFileSync(jsonPath, 'utf8')) as readonly (string | readonly number[])[];
  } catch (err) {
    // Only fall back on file-not-found; rethrow parse errors (corrupted cache)
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw err;
    }
    logger.debug(`BPE JSON cache not found for ${dataName}, falling back to JS module import`);
  }

  const { resolveEncodingAsync } = await import('gpt-tokenizer/resolveEncodingAsync');
  return resolveEncodingAsync(encodingName);
};

const loadEncoding = async (encodingName: TokenEncoding): Promise<CountTokensFn> => {
  const cached = encodingModules.get(encodingName);
  if (cached) {
    return cached;
  }

  const startTime = process.hrtime.bigint();

  const bpeRanks = await loadBpeRanks(encodingName);
  const encoder = GptEncoding.getEncodingApi(encodingName, () => bpeRanks);
  const countFn = encoder.countTokens.bind(encoder) as CountTokensFn;
  encodingModules.set(encodingName, countFn);

  const endTime = process.hrtime.bigint();
  const initTime = Number(endTime - startTime) / 1e6;
  logger.debug(`TokenCounter initialization for ${encodingName} took ${initTime.toFixed(2)}ms`);

  return countFn;
};

export class TokenCounter {
  private countFn: CountTokensFn | null = null;
  private readonly encodingName: TokenEncoding;

  constructor(encodingName: TokenEncoding) {
    this.encodingName = encodingName;
  }

  async init(): Promise<void> {
    this.countFn = await loadEncoding(this.encodingName);
  }

  public countTokens(content: string, filePath?: string): number {
    if (!this.countFn) {
      throw new Error('TokenCounter not initialized. Call init() first.');
    }

    try {
      // Use PLAIN_TEXT_OPTIONS to treat all content as ordinary text,
      // skipping gpt-tokenizer's default regex scan for special tokens.
      return this.countFn(content, PLAIN_TEXT_OPTIONS);
    } catch (error) {
      let message = '';
      if (error instanceof Error) {
        message = error.message;
      } else {
        message = String(error);
      }

      if (filePath) {
        logger.warn(`Failed to count tokens. path: ${filePath}, error: ${message}`);
      } else {
        logger.warn(`Failed to count tokens. error: ${message}`);
      }

      return 0;
    }
  }

  // No-op: gpt-tokenizer is pure JS, no WASM resources to free
  public free(): void {}
}
