import { describe, expect, test } from 'vitest';
import type { RenderContext } from '../../../../src/core/output/outputGeneratorTypes.js';
import {
  generateFilesSection,
  generateGitDiffsSection,
  generateGitLogsSection,
  generateStructureSection,
  generateSummarySection,
} from '../../../../src/core/output/skill/skillSectionGenerators.js';

const createMockContext = (overrides: Partial<RenderContext> = {}): RenderContext => ({
  generationHeader: 'Generated by Repomix',
  summaryPurpose: 'This file contains a packed representation of the entire repository.',
  summaryFileFormat: 'The content is organized as follows...',
  summaryUsageGuidelines: 'Use this file as context for AI assistants.',
  summaryNotes: 'Some files may have been excluded.',
  headerText: '',
  instruction: '',
  treeString: 'src/\n  index.ts\n  utils.ts',
  processedFiles: [
    { path: 'src/index.ts', content: 'console.log("hello");' },
    { path: 'src/utils.ts', content: 'export const sum = (a, b) => a + b;' },
  ],
  fileSummaryEnabled: true,
  directoryStructureEnabled: true,
  filesEnabled: true,
  escapeFileContent: false,
  markdownCodeBlockDelimiter: '```',
  gitDiffEnabled: false,
  gitDiffWorkTree: undefined,
  gitDiffStaged: undefined,
  gitLogEnabled: false,
  gitLogContent: undefined,
  gitLogCommits: undefined,
  ...overrides,
});

describe('skillSectionGenerators', () => {
  describe('generateSummarySection', () => {
    test('should generate summary section with all fields', () => {
      const context = createMockContext();
      const result = generateSummarySection(context);

      expect(result).toContain('Generated by Repomix');
      expect(result).toContain('# File Summary');
      expect(result).toContain('## Purpose');
      expect(result).toContain('This file contains a packed representation');
      expect(result).toContain('## File Format');
      expect(result).toContain('## Usage Guidelines');
      expect(result).toContain('## Notes');
    });
  });

  describe('generateStructureSection', () => {
    test('should generate structure section with tree string', () => {
      const context = createMockContext();
      const result = generateStructureSection(context);

      expect(result).toContain('# Directory Structure');
      expect(result).toContain('```');
      expect(result).toContain('src/');
      expect(result).toContain('index.ts');
    });

    test('should return empty string when directory structure is disabled', () => {
      const context = createMockContext({ directoryStructureEnabled: false });
      const result = generateStructureSection(context);

      expect(result).toBe('');
    });
  });

  describe('generateFilesSection', () => {
    test('should generate files section with all files', () => {
      const context = createMockContext();
      const result = generateFilesSection(context);

      expect(result).toContain('# Files');
      expect(result).toContain('## File: src/index.ts');
      expect(result).toContain('console.log("hello");');
      expect(result).toContain('## File: src/utils.ts');
      expect(result).toContain('export const sum');
    });

    test('should include syntax highlighting language', () => {
      const context = createMockContext();
      const result = generateFilesSection(context);

      expect(result).toContain('```typescript');
    });

    test('should return empty string when files are disabled', () => {
      const context = createMockContext({ filesEnabled: false });
      const result = generateFilesSection(context);

      expect(result).toBe('');
    });

    test('should handle files without known extensions', () => {
      const context = createMockContext({
        processedFiles: [{ path: 'Dockerfile', content: 'FROM node:18' }],
      });
      const result = generateFilesSection(context);

      expect(result).toContain('## File: Dockerfile');
      expect(result).toContain('FROM node:18');
    });
  });

  describe('generateGitDiffsSection', () => {
    test('should generate git diffs section when enabled', () => {
      const context = createMockContext({
        gitDiffEnabled: true,
        gitDiffWorkTree: '- old line\n+ new line',
        gitDiffStaged: '- staged old\n+ staged new',
      });
      const result = generateGitDiffsSection(context);

      expect(result).not.toBeUndefined();
      expect(result).toContain('# Git Diffs');
      expect(result).toContain('## Working Tree Changes');
      expect(result).toContain('```diff');
      expect(result).toContain('- old line');
      expect(result).toContain('+ new line');
      expect(result).toContain('## Staged Changes');
      expect(result).toContain('- staged old');
    });

    test('should return undefined when git diffs are disabled', () => {
      const context = createMockContext({ gitDiffEnabled: false });
      const result = generateGitDiffsSection(context);

      expect(result).toBeUndefined();
    });
  });

  describe('generateGitLogsSection', () => {
    test('should generate git logs section when enabled', () => {
      const context = createMockContext({
        gitLogEnabled: true,
        gitLogCommits: [
          {
            date: '2024-01-15',
            message: 'feat: add new feature',
            files: ['src/index.ts', 'src/feature.ts'],
          },
          {
            date: '2024-01-14',
            message: 'fix: bug fix',
            files: ['src/utils.ts'],
          },
        ],
      });
      const result = generateGitLogsSection(context);

      expect(result).not.toBeUndefined();
      expect(result).toContain('# Git Logs');
      expect(result).toContain('## Commit: 2024-01-15');
      expect(result).toContain('**Message:** feat: add new feature');
      expect(result).toContain('**Files:**');
      expect(result).toContain('- src/index.ts');
      expect(result).toContain('- src/feature.ts');
      expect(result).toContain('## Commit: 2024-01-14');
      expect(result).toContain('fix: bug fix');
    });

    test('should return undefined when git logs are disabled', () => {
      const context = createMockContext({ gitLogEnabled: false });
      const result = generateGitLogsSection(context);

      expect(result).toBeUndefined();
    });

    test('should return undefined when git log commits are undefined', () => {
      const context = createMockContext({
        gitLogEnabled: true,
        gitLogCommits: undefined,
      });
      const result = generateGitLogsSection(context);

      expect(result).toBeUndefined();
    });
  });
});
