name: Homebrew

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@b2a302b9a642580cae998e6ba2076ffd28e61317 # main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@b2a302b9a642580cae998e6ba2076ffd28e61317 # main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@b2a302b9a642580cae998e6ba2076ffd28e61317 # main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repomix
