name: Homebrew

on:
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@98cfa07b984a61682e6cd3a0833fad2006cc84ba # main
        with:
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@98cfa07b984a61682e6cd3a0833fad2006cc84ba # main

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@98cfa07b984a61682e6cd3a0833fad2006cc84ba # main
        with:
          token: ${{ secrets.COMMITTER_TOKEN }}
          formulae: repomix
